[package]
name = "jongo"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
lindera = { version = "3.0.7", features = ["embed-ipadic"] }
phf = { version = "0.13.1", features = ["macros"] }
wasm-bindgen = "0.2.123"
web-sys = { version = "0.3.100", features = ["Window", "Document", "Element", "HtmlElement", "Node", "MouseEvent", "KeyboardEvent", "EventTarget", "console", "Range", "CaretPosition", "DomRect", "Selection", "NodeList"] }

[lib]
crate-type = ["cdylib", "rlib"]